# This is a basic workflow to help you get started with Actions

name: CI-cygwin

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
    inputs:
      MYENV:
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  simple_build_cygwin:
    runs-on: windows-latest
    steps:
      - name: Setup Git
        shell: cmd
        run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cygwin
        id: cygwin
        uses: cygwin/cygwin-install-action@v6
        env:
          MYENV: ${{ inputs.MYENV }}
        with:
          packages: >-
            automake autoconf bash coreutils sed grep findutils pkg-config make gcc-g++ perl python3 \
            tcl-tk-devel tcl-devel libreadline-devel libncurses-devel \
            libX11-devel libX11-xcb-devel libICE-devel libXi-devel libXmu-devel libXext-devel \
            libcairo-devel libGL-devel libGLU-devel zlib-devel

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: System Info
        # Windows bash has igncr option, the project should be Unix EOL compatible
        shell: bash --noprofile --norc -e -o pipefail -o igncr {0}
        run: |
          set -o
          set +e
          echo MYENV=$MYENV
          test -f /etc/os-release && cat /etc/os-release
          cygcheck -s
          cygcheck --inst -i cygwin
          cygcheck --inst -i tk-devel
          cygcheck --inst -i tcl-tk-devel
          uname -a
          systeminfo
          cc -v
          ld -v
          make --version
          gmake --version # seems older version
          sed --version
          pwd
          ls -lah
          whoami
          env | grep -v "TOKEN" | grep -v "SECRET" | sort
          which more # /usr/bin/more
          nproc=$(nproc)
          export nproc
          echo "nproc=$nproc"

          echo "### cc -dM -E - | sort :"
          echo | cc -dM -E - | sort
          echo "### c++ -dM -E -x c++ - | sort :"
          echo | c++ -dM -E -x c++ - | sort
          echo "###"

          git config --global --add safe.directory "$(pwd)"

          dirs="."
          [ -d /usr/local ]           && dirs="$dirs /usr/local"
          [ -d /usr ]                 && dirs="$dirs /usr"
          [ -d /opt ]                 && dirs="$dirs /opt"
          [ -d /usr/include ]         && dirs="$dirs /usr/include"
          [ -d /usr/X11R6 ]           && dirs="$dirs /usr/X11R6"
          [ -d /usr/share/pkgconfig ] && dirs="$dirs /usr/share/pkgconfig"
          find $dirs -type f \( -name "tkConfig.sh" -or -name "tclConfig.sh" \) -print
          find $dirs -type f \( -name "lib*cairo*" -or -name "lib*tk*" -or -name "lib*tcl*" \) -print
          find $dirs -type f \( -name "libX11*" -or -name "libXi*" -or -name "libXmu*" -or -name "libXext*" -or -name "libICE*" \) -print
          find $dirs -type f \( -name "tcl.h" -or -iname "Xlib*.h" -or -name "cairo.h" \) -print
          find $dirs -type f \( -name "tcl*.pc" -or -name "tk*.pc" -or -name "*cairo*.pc" -or -name "freeglut*.pc" \) -print
          find $dirs -type f \( -name "tclsh" -or -name "tclsh[89]*" -or -name "wish" -or -name "wish[89]*" \) -print
          grep cairo_user_to_device /usr/local/include/cairo*.h /usr/local/include/cairo/cairo*.h
          nm -D /usr/local/lib/libcairo.so.* | grep cairo_user_to_device
          # freeglut # not found
          # pthread # not found
          for pkg in x11 cairo freeglut tcl tk pthread; \
          do \
            echo "### pkg-config --libs --cflags ${pkg} :"; \
            pkg-config --libs --cflags "$pkg"; \
          done
          # FIXME The build does not properly use this information above, it was just used a
          # diagnostics to get the build to complete.

          # Help identify files with CRNL EOLs that might not work as expected (--info will report only not change)
          find "$GITHUB_WORKSPACE" -type f \( -name "Makefile" -or -name "*.mak" -or -name "configure" -or -name "*.sh" \) -exec dos2unix --info {} \;

      - name: Build
        shell: bash --noprofile --norc -e -o pipefail -o igncr {0}
        run: |
          set -o pipefail
          set -e

          # /usr/local/lib/tcl8.7/tclConfig.sh
          # /usr/local/lib/tk8.7/tkConfig.sh
          # Need this to provide -I/usr/local/include because tcltk/*.c accesses <X11/Xlib.h>
          # headers but is not using GR_CFLAGS
          # CPPFLAGS want this extra option for depends and compile
          #CPPFLAGS="-I/usr/local/include"
          #export CPPFLAGS
          with_x11_libsdir=$(  pkg-config --libs-only-L   x11    | sed -e 's/-L//g')
          with_x11_incsdir=$(  pkg-config --cflags-only-I x11    | sed -e 's/-I//g')
          with_tcl_libsdir=$(  pkg-config --libs-only-L   tcl    | sed -e 's/-L//g')
          [ -z "$with_tcl_libsdir" ] && with_tcl_libsdir=$(find /usr -type f -name tclConfig.sh -printf "%h\n" | head -n1)
          with_tk_libsdir=$(   pkg-config --libs-only-L   tk     | sed -e 's/-L//g')
          [ -z "$with_tk_libsdir" ] && with_tk_libsdir=$(find /usr -type f -name tkConfig.sh -printf "%h\n" | head -n1)
          with_cairo_libsdir=$(pkg-config --libs-only-L   cairo  | sed -e 's/-L//g') # multiple
          echo --x-libraries=${with_x11_libsdir} --x-includes=${with_x11_incsdir} --with-tcl=${with_tcl_libsdir} --with-tk=${with_tk_libsdir} --with-cairo=/usr/local/include ${with_cairo_libsdir}
          # The only really important ones as --with-tcl and --with-tk the others
          CFLAGS="$CFLAGS -std=c17 -g"
          export CFLAGS
          echo CFLAGS=$CFLAGS
          echo CXXFLAGS=$CXXFLAGS
          echo CPPFLAGS=$CPPFLAGS
          echo LDFLAGS=$LDFLAGS
          echo LIBS=$LIBS
          ./configure ${with_x11_libsdir:+--x-libraries=}${with_x11_libsdir} ${with_x11_incsdir:+--x-includes=}${with_x11_incsdir} --with-tcl=${with_tcl_libsdir} --with-tk=${with_tk_libsdir} --with-cairo=/usr/local/include 2>&1 | tee CONFIGURE.LOG
          unset CFLAGS
          unset CXXFLAGS
          unset CPPFLAGS
          unset LDFLAGS
          unset LIBS

          echo "===== config.log ====="
          cat scripts/config.log
          echo "===== config.log ====="

          echo "===== defs.mak ====="
          cat defs.mak
          echo "===== defs.mak ====="

          make database/database.h
          make 2>&1 | tee MAKE.LOG

      - name: Install
        shell: bash --noprofile --norc -e -o pipefail -o igncr {0}
        run: |
          make install 2>&1 | tee INSTALL.LOG

          set +e
          dirs="."
          [ -d /usr/local ] && dirs="$dirs /usr/local"
          [ -d /opt ]       && dirs="$dirs /opt"
          find $dirs -type f \( -name "magicdnull*" -or -name "magicexec*" -or -name "*magic*.so" -or -name "*magic*.dll" \) -exec ldd {} \;

      - name: Post Install
        shell: cmd
        run: |
          set
          :: call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          :: Check if VCToolsRedistDir is set
          if not defined VCToolsRedistDir (
            echo Error: Environment variable VCToolsRedistDir is not set.
            exit /b 1
          )
          dumpbin
          echo DONE
          :: find $dirs -type f \( -name "magicdnull*" -or -name "magicexec*" -or -name "*magic*.so" -or -name "*magic*.dll" \) -exec dumpbin /imports {} \;

      - name: Kick Tyres Test
        shell: bash --noprofile --norc -e -o pipefail -o igncr {0}
        run: |
          set +e
          hash -r || true
          PATH="$PATH:/usr/local/bin"
          export PATH
          which magic
          magic --version || true

          echo "version; quit" | magic -d null -noconsole -nowindow -T cmos
          true
