# This is a basic workflow to help you get started with Actions

name: CI-freebsd

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  simple_build_freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: FreeBSD shell actions
        id: freebsd
        uses: vmactions/freebsd-vm@v1
        with:
          envs: MYENV
          usesh: true
          prepare: |
            echo pkg_add devel/gmake lang/tcl/8.6 x11/tk/8.6 graphics/cairo graphics/freeglut devel/git
            # zlib is in base
            pkg install -y gmake tcl87 tk87 cairo freeglut git
          run: |
            pwd
            ls -lah
            whoami
            env
            freebsd-version
            sysctl hw.model
            sysctl hw.ncpu
            sysctl hw.physmem
            sysctl hw.usermem
            set +e
            uname -a
            cc -v
            ld -v
            nproc=$(sysctl hw.ncpu | sed -e  's/.*=//')
            export nproc
            echo "nproc=$nproc"
            make --version
            gmake --version

            git config --global --add safe.directory "$(pwd)"

            ./configure --with-tcl=/usr/local/lib --with-tk=/usr/local/lib --with-cairo=/usr/local/include 2>&1 | tee CONFIGURE.LOG

            echo "===== defs.mak ====="
            cat defs.mak
            echo "===== defs.mak ====="

            gmake database/database.h
            gmake 2>&1 | tee MAKE.LOG

            gmake install 2>&1 | tee INSTALL.LOG
            
            find . -type f \( -name "magic" -or -name "magicdnull" -or -name "magicexec" -or -name "*.so" \) -exec ldd {} \;
            
            find . -type f \( -name "lib*cairo*" -or -name "lib*tk*" -or -name "lib*tcl*" \)

            hash -r || true
            which magic
            magic --version
